name: tute6
version: 0.1.0.0
github: "githubuser/intro"
license: BSD3
author: "Arthur Mahéo"
maintainer: "arthur.maheo@monash.edu"
copyright: "2019 Arthur Mahéo"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/intro#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: []

tests:
  batch:
    main: Spec.hs
    source-dirs: test
    ghc-options: []
    dependencies:
      - Glob
      - doctest
      - QuickCheck
  watch:
    main: Watch.hs
    source-dirs: watch
    ghc-options: []
    dependencies:
      - Glob
      - doctest
      - QuickCheck
      - fsnotify
      - ansi-terminal
